//
// Generated by JTB 1.3.2
//

package ant.parser.visitor;
import ant.parser.syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class DepthFirstVisitor implements Visitor {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeListOptional n) {
      if ( n.present() )
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
            e.nextElement().accept(this);
   }

   public void visit(NodeOptional n) {
      if ( n.present() )
         n.node.accept(this);
   }

   public void visit(NodeSequence n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeToken n) { }

   //
   // User-generated visitor methods below
   //

   /**
    * nodeOptional -> ( Eol() )?
    * nodeListOptional -> ( Block() )*
    * nodeToken -> <EOF>
    */
   public void visit(Program n) {
      n.nodeOptional.accept(this);
      n.nodeListOptional.accept(this);
      n.nodeToken.accept(this);
   }

   /**
    * ident -> Ident()
    * nodeToken -> ":"
    * eol -> Eol()
    * nodeListOptional -> ( Instr() )*
    */
   public void visit(Block n) {
      n.ident.accept(this);
      n.nodeToken.accept(this);
      n.eol.accept(this);
      n.nodeListOptional.accept(this);
   }

   /**
    * nodeChoice -> ( Sense() | Mark() | Unmark() | PickUp() | Drop() | Goto() | Turn() | Move() | Flip() )
    */
   public void visit(Instr n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "Sense"
    * sensedir -> Sensedir()
    * ident -> Ident()
    * ident1 -> Ident()
    * cond -> Cond()
    * eol -> Eol()
    */
   public void visit(Sense n) {
      n.nodeToken.accept(this);
      n.sensedir.accept(this);
      n.ident.accept(this);
      n.ident1.accept(this);
      n.cond.accept(this);
      n.eol.accept(this);
   }

   /**
    * nodeToken -> "Mark"
    * litInt -> LitInt()
    * eol -> Eol()
    */
   public void visit(Mark n) {
      n.nodeToken.accept(this);
      n.litInt.accept(this);
      n.eol.accept(this);
   }

   /**
    * nodeToken -> "Unmark"
    * litInt -> LitInt()
    * eol -> Eol()
    */
   public void visit(Unmark n) {
      n.nodeToken.accept(this);
      n.litInt.accept(this);
      n.eol.accept(this);
   }

   /**
    * nodeToken -> "PickUp"
    * ident -> Ident()
    * eol -> Eol()
    */
   public void visit(PickUp n) {
      n.nodeToken.accept(this);
      n.ident.accept(this);
      n.eol.accept(this);
   }

   /**
    * nodeToken -> "Drop"
    * eol -> Eol()
    */
   public void visit(Drop n) {
      n.nodeToken.accept(this);
      n.eol.accept(this);
   }

   /**
    * nodeToken -> "Turn"
    * direction -> Direction()
    * eol -> Eol()
    */
   public void visit(Turn n) {
      n.nodeToken.accept(this);
      n.direction.accept(this);
      n.eol.accept(this);
   }

   /**
    * nodeToken -> "Move"
    * ident -> Ident()
    * eol -> Eol()
    */
   public void visit(Move n) {
      n.nodeToken.accept(this);
      n.ident.accept(this);
      n.eol.accept(this);
   }

   /**
    * nodeToken -> "Flip"
    * litInt -> LitInt()
    * ident -> Ident()
    * ident1 -> Ident()
    * eol -> Eol()
    */
   public void visit(Flip n) {
      n.nodeToken.accept(this);
      n.litInt.accept(this);
      n.ident.accept(this);
      n.ident1.accept(this);
      n.eol.accept(this);
   }

   /**
    * nodeToken -> "Goto"
    * ident -> Ident()
    * eol -> Eol()
    */
   public void visit(Goto n) {
      n.nodeToken.accept(this);
      n.ident.accept(this);
      n.eol.accept(this);
   }

   /**
    * nodeChoice -> ( Left() | Right() )
    */
   public void visit(Direction n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "Left"
    */
   public void visit(Left n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "Right"
    */
   public void visit(Right n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeChoice -> ( Friend() | Foe() | FriendWithFood() | FoeWithFood() | Food() | Rock() | Marker() | FoeMarker() | Home() | FoeHome() )
    */
   public void visit(Cond n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "Friend"
    */
   public void visit(Friend n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "Foe"
    */
   public void visit(Foe n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "FriendWithFood"
    */
   public void visit(FriendWithFood n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "FoeWithFood"
    */
   public void visit(FoeWithFood n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "Food"
    */
   public void visit(Food n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "Rock"
    */
   public void visit(Rock n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "Marker"
    * litInt -> LitInt()
    */
   public void visit(Marker n) {
      n.nodeToken.accept(this);
      n.litInt.accept(this);
   }

   /**
    * nodeToken -> "FoeMarker"
    */
   public void visit(FoeMarker n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "Home"
    */
   public void visit(Home n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "FoeHome"
    */
   public void visit(FoeHome n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeChoice -> ( Here() | Ahead() | LeftAhead() | RightAhead() )
    */
   public void visit(Sensedir n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeToken -> "Here"
    */
   public void visit(Here n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "Ahead"
    */
   public void visit(Ahead n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "LeftAhead"
    */
   public void visit(LeftAhead n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> "RightAhead"
    */
   public void visit(RightAhead n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeToken -> <PlainIdent>
    */
   public void visit(Ident n) {
      n.nodeToken.accept(this);
   }

   /**
    * nodeChoice -> ( <Digits> | <NegDigits> )
    */
   public void visit(LitInt n) {
      n.nodeChoice.accept(this);
   }

   /**
    * nodeList -> ( <Eol> )+
    */
   public void visit(Eol n) {
      n.nodeList.accept(this);
   }

}
