//
// Generated by JTB 1.3.2
//

package ant.parser.visitor;
import ant.parser.syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJDepthFirst<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * nodeOptional -> ( Eol() )?
    * nodeListOptional -> ( Block() )*
    * nodeToken -> <EOF>
    */
   public R visit(Program n, A argu) {
      R _ret=null;
      n.nodeOptional.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * ident -> Ident()
    * nodeToken -> ":"
    * eol -> Eol()
    * nodeListOptional -> ( Instr() )*
    */
   public R visit(Block n, A argu) {
      R _ret=null;
      n.ident.accept(this, argu);
      n.nodeToken.accept(this, argu);
      n.eol.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      return _ret;
   }

   /**
    * nodeChoice -> ( Sense() | Mark() | Unmark() | PickUp() | Drop() | Goto() | Turn() | Move() | Flip() )
    */
   public R visit(Instr n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "Sense"
    * sensedir -> Sensedir()
    * ident -> Ident()
    * ident1 -> Ident()
    * cond -> Cond()
    * eol -> Eol()
    */
   public R visit(Sense n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.sensedir.accept(this, argu);
      n.ident.accept(this, argu);
      n.ident1.accept(this, argu);
      n.cond.accept(this, argu);
      n.eol.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "Mark"
    * litInt -> LitInt()
    * eol -> Eol()
    */
   public R visit(Mark n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.litInt.accept(this, argu);
      n.eol.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "Unmark"
    * litInt -> LitInt()
    * eol -> Eol()
    */
   public R visit(Unmark n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.litInt.accept(this, argu);
      n.eol.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "PickUp"
    * ident -> Ident()
    * eol -> Eol()
    */
   public R visit(PickUp n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.ident.accept(this, argu);
      n.eol.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "Drop"
    * eol -> Eol()
    */
   public R visit(Drop n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.eol.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "Turn"
    * direction -> Direction()
    * eol -> Eol()
    */
   public R visit(Turn n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.direction.accept(this, argu);
      n.eol.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "Move"
    * ident -> Ident()
    * eol -> Eol()
    */
   public R visit(Move n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.ident.accept(this, argu);
      n.eol.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "Flip"
    * litInt -> LitInt()
    * ident -> Ident()
    * ident1 -> Ident()
    * eol -> Eol()
    */
   public R visit(Flip n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.litInt.accept(this, argu);
      n.ident.accept(this, argu);
      n.ident1.accept(this, argu);
      n.eol.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "Goto"
    * ident -> Ident()
    * eol -> Eol()
    */
   public R visit(Goto n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.ident.accept(this, argu);
      n.eol.accept(this, argu);
      return _ret;
   }

   /**
    * nodeChoice -> ( Left() | Right() )
    */
   public R visit(Direction n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "Left"
    */
   public R visit(Left n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "Right"
    */
   public R visit(Right n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * nodeChoice -> ( Friend() | Foe() | FriendWithFood() | FoeWithFood() | Food() | Rock() | Marker() | FoeMarker() | Home() | FoeHome() )
    */
   public R visit(Cond n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "Friend"
    */
   public R visit(Friend n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "Foe"
    */
   public R visit(Foe n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "FriendWithFood"
    */
   public R visit(FriendWithFood n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "FoeWithFood"
    */
   public R visit(FoeWithFood n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "Food"
    */
   public R visit(Food n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "Rock"
    */
   public R visit(Rock n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "Marker"
    * litInt -> LitInt()
    */
   public R visit(Marker n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.litInt.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "FoeMarker"
    */
   public R visit(FoeMarker n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "Home"
    */
   public R visit(Home n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "FoeHome"
    */
   public R visit(FoeHome n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * nodeChoice -> ( Here() | Ahead() | LeftAhead() | RightAhead() )
    */
   public R visit(Sensedir n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "Here"
    */
   public R visit(Here n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "Ahead"
    */
   public R visit(Ahead n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "LeftAhead"
    */
   public R visit(LeftAhead n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> "RightAhead"
    */
   public R visit(RightAhead n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * nodeToken -> <PlainIdent>
    */
   public R visit(Ident n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * nodeChoice -> ( <Digits> | <NegDigits> )
    */
   public R visit(LitInt n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * nodeList -> ( <Eol> )+
    */
   public R visit(Eol n, A argu) {
      R _ret=null;
      n.nodeList.accept(this, argu);
      return _ret;
   }

}
