//
// Generated by JTB 1.3.2
//

package ant.parser.visitor;
import ant.parser.syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJVoidDepthFirst<A> implements GJVoidVisitor<A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n, A argu) {
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
   }

   public void visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
      }
   }

   public void visit(NodeOptional n, A argu) {
      if ( n.present() )
         n.node.accept(this,argu);
   }

   public void visit(NodeSequence n, A argu) {
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
   }

   public void visit(NodeToken n, A argu) {}

   //
   // User-generated visitor methods below
   //

   /**
    * nodeOptional -> ( Eol() )?
    * nodeListOptional -> ( Block() )*
    * nodeToken -> <EOF>
    */
   public void visit(Program n, A argu) {
      n.nodeOptional.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      n.nodeToken.accept(this, argu);
   }

   /**
    * ident -> Ident()
    * nodeToken -> ":"
    * eol -> Eol()
    * nodeListOptional -> ( Instr() )*
    */
   public void visit(Block n, A argu) {
      n.ident.accept(this, argu);
      n.nodeToken.accept(this, argu);
      n.eol.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
   }

   /**
    * nodeChoice -> ( Sense() | Mark() | Unmark() | PickUp() | Drop() | Goto() | Turn() | Move() | Flip() )
    */
   public void visit(Instr n, A argu) {
      n.nodeChoice.accept(this, argu);
   }

   /**
    * nodeToken -> "Sense"
    * sensedir -> Sensedir()
    * ident -> Ident()
    * ident1 -> Ident()
    * cond -> Cond()
    * eol -> Eol()
    */
   public void visit(Sense n, A argu) {
      n.nodeToken.accept(this, argu);
      n.sensedir.accept(this, argu);
      n.ident.accept(this, argu);
      n.ident1.accept(this, argu);
      n.cond.accept(this, argu);
      n.eol.accept(this, argu);
   }

   /**
    * nodeToken -> "Mark"
    * litInt -> LitInt()
    * eol -> Eol()
    */
   public void visit(Mark n, A argu) {
      n.nodeToken.accept(this, argu);
      n.litInt.accept(this, argu);
      n.eol.accept(this, argu);
   }

   /**
    * nodeToken -> "Unmark"
    * litInt -> LitInt()
    * eol -> Eol()
    */
   public void visit(Unmark n, A argu) {
      n.nodeToken.accept(this, argu);
      n.litInt.accept(this, argu);
      n.eol.accept(this, argu);
   }

   /**
    * nodeToken -> "PickUp"
    * ident -> Ident()
    * eol -> Eol()
    */
   public void visit(PickUp n, A argu) {
      n.nodeToken.accept(this, argu);
      n.ident.accept(this, argu);
      n.eol.accept(this, argu);
   }

   /**
    * nodeToken -> "Drop"
    * eol -> Eol()
    */
   public void visit(Drop n, A argu) {
      n.nodeToken.accept(this, argu);
      n.eol.accept(this, argu);
   }

   /**
    * nodeToken -> "Turn"
    * direction -> Direction()
    * eol -> Eol()
    */
   public void visit(Turn n, A argu) {
      n.nodeToken.accept(this, argu);
      n.direction.accept(this, argu);
      n.eol.accept(this, argu);
   }

   /**
    * nodeToken -> "Move"
    * ident -> Ident()
    * eol -> Eol()
    */
   public void visit(Move n, A argu) {
      n.nodeToken.accept(this, argu);
      n.ident.accept(this, argu);
      n.eol.accept(this, argu);
   }

   /**
    * nodeToken -> "Flip"
    * litInt -> LitInt()
    * ident -> Ident()
    * ident1 -> Ident()
    * eol -> Eol()
    */
   public void visit(Flip n, A argu) {
      n.nodeToken.accept(this, argu);
      n.litInt.accept(this, argu);
      n.ident.accept(this, argu);
      n.ident1.accept(this, argu);
      n.eol.accept(this, argu);
   }

   /**
    * nodeToken -> "Goto"
    * ident -> Ident()
    * eol -> Eol()
    */
   public void visit(Goto n, A argu) {
      n.nodeToken.accept(this, argu);
      n.ident.accept(this, argu);
      n.eol.accept(this, argu);
   }

   /**
    * nodeChoice -> ( Left() | Right() )
    */
   public void visit(Direction n, A argu) {
      n.nodeChoice.accept(this, argu);
   }

   /**
    * nodeToken -> "Left"
    */
   public void visit(Left n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "Right"
    */
   public void visit(Right n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeChoice -> ( Friend() | Foe() | FriendWithFood() | FoeWithFood() | Food() | Rock() | Marker() | FoeMarker() | Home() | FoeHome() )
    */
   public void visit(Cond n, A argu) {
      n.nodeChoice.accept(this, argu);
   }

   /**
    * nodeToken -> "Friend"
    */
   public void visit(Friend n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "Foe"
    */
   public void visit(Foe n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "FriendWithFood"
    */
   public void visit(FriendWithFood n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "FoeWithFood"
    */
   public void visit(FoeWithFood n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "Food"
    */
   public void visit(Food n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "Rock"
    */
   public void visit(Rock n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "Marker"
    * litInt -> LitInt()
    */
   public void visit(Marker n, A argu) {
      n.nodeToken.accept(this, argu);
      n.litInt.accept(this, argu);
   }

   /**
    * nodeToken -> "FoeMarker"
    */
   public void visit(FoeMarker n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "Home"
    */
   public void visit(Home n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "FoeHome"
    */
   public void visit(FoeHome n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeChoice -> ( Here() | Ahead() | LeftAhead() | RightAhead() )
    */
   public void visit(Sensedir n, A argu) {
      n.nodeChoice.accept(this, argu);
   }

   /**
    * nodeToken -> "Here"
    */
   public void visit(Here n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "Ahead"
    */
   public void visit(Ahead n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "LeftAhead"
    */
   public void visit(LeftAhead n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> "RightAhead"
    */
   public void visit(RightAhead n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeToken -> <PlainIdent>
    */
   public void visit(Ident n, A argu) {
      n.nodeToken.accept(this, argu);
   }

   /**
    * nodeChoice -> ( <Digits> | <NegDigits> )
    */
   public void visit(LitInt n, A argu) {
      n.nodeChoice.accept(this, argu);
   }

   /**
    * nodeList -> ( <Eol> )+
    */
   public void visit(Eol n, A argu) {
      n.nodeList.accept(this, argu);
   }

}
