//
// Generated by JTB 1.3.2
//

package ant.parser.visitor;
import ant.parser.syntaxtree.*;
import java.util.*;

/**
 * All void visitors must implement this interface.
 */

public interface Visitor {

   //
   // void Auto class visitors
   //

   public void visit(NodeList n);
   public void visit(NodeListOptional n);
   public void visit(NodeOptional n);
   public void visit(NodeSequence n);
   public void visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * nodeOptional -> ( Eol() )?
    * nodeListOptional -> ( Block() )*
    * nodeToken -> <EOF>
    */
   public void visit(Program n);

   /**
    * ident -> Ident()
    * nodeToken -> ":"
    * eol -> Eol()
    * nodeListOptional -> ( Instr() )*
    */
   public void visit(Block n);

   /**
    * nodeChoice -> ( Sense() | Mark() | Unmark() | PickUp() | Drop() | Goto() | Turn() | Move() | Flip() )
    */
   public void visit(Instr n);

   /**
    * nodeToken -> "Sense"
    * sensedir -> Sensedir()
    * ident -> Ident()
    * ident1 -> Ident()
    * cond -> Cond()
    * eol -> Eol()
    */
   public void visit(Sense n);

   /**
    * nodeToken -> "Mark"
    * litInt -> LitInt()
    * eol -> Eol()
    */
   public void visit(Mark n);

   /**
    * nodeToken -> "Unmark"
    * litInt -> LitInt()
    * eol -> Eol()
    */
   public void visit(Unmark n);

   /**
    * nodeToken -> "PickUp"
    * ident -> Ident()
    * eol -> Eol()
    */
   public void visit(PickUp n);

   /**
    * nodeToken -> "Drop"
    * eol -> Eol()
    */
   public void visit(Drop n);

   /**
    * nodeToken -> "Turn"
    * direction -> Direction()
    * eol -> Eol()
    */
   public void visit(Turn n);

   /**
    * nodeToken -> "Move"
    * ident -> Ident()
    * eol -> Eol()
    */
   public void visit(Move n);

   /**
    * nodeToken -> "Flip"
    * litInt -> LitInt()
    * ident -> Ident()
    * ident1 -> Ident()
    * eol -> Eol()
    */
   public void visit(Flip n);

   /**
    * nodeToken -> "Goto"
    * ident -> Ident()
    * eol -> Eol()
    */
   public void visit(Goto n);

   /**
    * nodeChoice -> ( Left() | Right() )
    */
   public void visit(Direction n);

   /**
    * nodeToken -> "Left"
    */
   public void visit(Left n);

   /**
    * nodeToken -> "Right"
    */
   public void visit(Right n);

   /**
    * nodeChoice -> ( Friend() | Foe() | FriendWithFood() | FoeWithFood() | Food() | Rock() | Marker() | FoeMarker() | Home() | FoeHome() )
    */
   public void visit(Cond n);

   /**
    * nodeToken -> "Friend"
    */
   public void visit(Friend n);

   /**
    * nodeToken -> "Foe"
    */
   public void visit(Foe n);

   /**
    * nodeToken -> "FriendWithFood"
    */
   public void visit(FriendWithFood n);

   /**
    * nodeToken -> "FoeWithFood"
    */
   public void visit(FoeWithFood n);

   /**
    * nodeToken -> "Food"
    */
   public void visit(Food n);

   /**
    * nodeToken -> "Rock"
    */
   public void visit(Rock n);

   /**
    * nodeToken -> "Marker"
    * litInt -> LitInt()
    */
   public void visit(Marker n);

   /**
    * nodeToken -> "FoeMarker"
    */
   public void visit(FoeMarker n);

   /**
    * nodeToken -> "Home"
    */
   public void visit(Home n);

   /**
    * nodeToken -> "FoeHome"
    */
   public void visit(FoeHome n);

   /**
    * nodeChoice -> ( Here() | Ahead() | LeftAhead() | RightAhead() )
    */
   public void visit(Sensedir n);

   /**
    * nodeToken -> "Here"
    */
   public void visit(Here n);

   /**
    * nodeToken -> "Ahead"
    */
   public void visit(Ahead n);

   /**
    * nodeToken -> "LeftAhead"
    */
   public void visit(LeftAhead n);

   /**
    * nodeToken -> "RightAhead"
    */
   public void visit(RightAhead n);

   /**
    * nodeToken -> <PlainIdent>
    */
   public void visit(Ident n);

   /**
    * nodeChoice -> ( <Digits> | <NegDigits> )
    */
   public void visit(LitInt n);

   /**
    * nodeList -> ( <Eol> )+
    */
   public void visit(Eol n);

}

