//
// Generated by JTB 1.3.2
//

package ant.parser.syntaxtree;

/**
 * Grammar production:
 * ident -> Ident()
 * nodeToken -> ":"
 * eol -> Eol()
 * nodeListOptional -> ( Instr() )*
 */
public class Block implements Node {
   public Ident ident;
   public NodeToken nodeToken;
   public Eol eol;
   public NodeListOptional nodeListOptional;

   public Block(Ident n0, NodeToken n1, Eol n2, NodeListOptional n3) {
      ident = n0;
      nodeToken = n1;
      eol = n2;
      nodeListOptional = n3;
   }

   public Block(Ident n0, Eol n1, NodeListOptional n2) {
      ident = n0;
      nodeToken = new NodeToken(":");
      eol = n1;
      nodeListOptional = n2;
   }

   public void accept(ant.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(ant.parser.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(ant.parser.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(ant.parser.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

