//
// Generated by JTB 1.3.2
//

package ant.parser.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "Flip"
 * litInt -> LitInt()
 * ident -> Ident()
 * ident1 -> Ident()
 * eol -> Eol()
 */
public class Flip implements Node {
   public NodeToken nodeToken;
   public LitInt litInt;
   public Ident ident;
   public Ident ident1;
   public Eol eol;

   public Flip(NodeToken n0, LitInt n1, Ident n2, Ident n3, Eol n4) {
      nodeToken = n0;
      litInt = n1;
      ident = n2;
      ident1 = n3;
      eol = n4;
   }

   public Flip(LitInt n0, Ident n1, Ident n2, Eol n3) {
      nodeToken = new NodeToken("Flip");
      litInt = n0;
      ident = n1;
      ident1 = n2;
      eol = n3;
   }

   public void accept(ant.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(ant.parser.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(ant.parser.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(ant.parser.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

