//
// Generated by JTB 1.3.2
//

package ant.parser.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "Marker"
 * litInt -> LitInt()
 */
public class Marker implements Node {
   public NodeToken nodeToken;
   public LitInt litInt;

   public Marker(NodeToken n0, LitInt n1) {
      nodeToken = n0;
      litInt = n1;
   }

   public Marker(LitInt n0) {
      nodeToken = new NodeToken("Marker");
      litInt = n0;
   }

   public void accept(ant.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(ant.parser.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(ant.parser.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(ant.parser.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

