//
// Generated by JTB 1.3.2
//

package ant.parser.syntaxtree;

/**
 * Grammar production:
 * nodeToken -> "Mark"
 * litInt -> LitInt()
 * eol -> Eol()
 */
public class Mark implements Node {
   public NodeToken nodeToken;
   public LitInt litInt;
   public Eol eol;

   public Mark(NodeToken n0, LitInt n1, Eol n2) {
      nodeToken = n0;
      litInt = n1;
      eol = n2;
   }

   public Mark(LitInt n0, Eol n1) {
      nodeToken = new NodeToken("Mark");
      litInt = n0;
      eol = n1;
   }

   public void accept(ant.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(ant.parser.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(ant.parser.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(ant.parser.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

